# Place this file in the root of your '3tierDevOpsCICD' project

services:
  # 1. The Frontend (Static Nginx server)
  # This service is built from your Frontend/Dockerfile
  frontend:
    build: ./Frontend
    # No ports exposed, as our 'proxy' will handle traffic

  # 2. The Backend (Node.js API)
  # This service is built from your Backend/Dockerfile
  backend:
    build: ./Backend
    # We load the .env file from the Backend directory
    # This file contains your AWS RDS credentials (DB_HOST, DB_USER, etc.)
    env_file:
      - ./Backend/.env
    # No 'depends_on' needed as the DB is external

  # 3. The Proxy (Local ALB Simulator)
  # This is the single entry point for your app.
  proxy:
    image: nginx:1.25-alpine
    restart: always
    ports:
      # Access your app at http://localhost:8080
      - "8080:80"
    volumes:
      # Mount the proxy config file
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend